name: pronto
on: [pull_request]

jobs:
  pronto:
    runs-on: ubuntu-24.04
    if: github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name && github.actor != 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: |
          git fetch --no-tags --prune origin +refs/heads/*:refs/remotes/origin/*
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup NPM
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version-file: ".node-version"
      - name: Install node packages
        run: npm clean-install
      - name: Fetch base branch
        run: git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}
      - name: Run pronto
        run: bundle exec pronto run -f text --exit-code -c ${{ github.event.pull_request.base.ref }}